"""[change] saved and action

Revision ID: 172e2aace1d4
Revises: 
Create Date: 2023-10-26 15:32:38.041888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172e2aace1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('save_id')

    # ### end Alembic commands ###
